/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as MarketAnalysisRouteImport } from './routes/market-analysis'
import { Route as LocalityInsightsRouteImport } from './routes/locality-insights'
import { Route as BudgetPlannerRouteImport } from './routes/budget-planner'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketAnalysisRoute = MarketAnalysisRouteImport.update({
  id: '/market-analysis',
  path: '/market-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalityInsightsRoute = LocalityInsightsRouteImport.update({
  id: '/locality-insights',
  path: '/locality-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetPlannerRoute = BudgetPlannerRouteImport.update({
  id: '/budget-planner',
  path: '/budget-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budget-planner': typeof BudgetPlannerRoute
  '/locality-insights': typeof LocalityInsightsRoute
  '/market-analysis': typeof MarketAnalysisRoute
  '/predictor': typeof PredictorRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budget-planner': typeof BudgetPlannerRoute
  '/locality-insights': typeof LocalityInsightsRoute
  '/market-analysis': typeof MarketAnalysisRoute
  '/predictor': typeof PredictorRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/budget-planner': typeof BudgetPlannerRoute
  '/locality-insights': typeof LocalityInsightsRoute
  '/market-analysis': typeof MarketAnalysisRoute
  '/predictor': typeof PredictorRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/budget-planner'
    | '/locality-insights'
    | '/market-analysis'
    | '/predictor'
    | '/recommendations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/budget-planner'
    | '/locality-insights'
    | '/market-analysis'
    | '/predictor'
    | '/recommendations'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/budget-planner'
    | '/locality-insights'
    | '/market-analysis'
    | '/predictor'
    | '/recommendations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  BudgetPlannerRoute: typeof BudgetPlannerRoute
  LocalityInsightsRoute: typeof LocalityInsightsRoute
  MarketAnalysisRoute: typeof MarketAnalysisRoute
  PredictorRoute: typeof PredictorRoute
  RecommendationsRoute: typeof RecommendationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-analysis': {
      id: '/market-analysis'
      path: '/market-analysis'
      fullPath: '/market-analysis'
      preLoaderRoute: typeof MarketAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locality-insights': {
      id: '/locality-insights'
      path: '/locality-insights'
      fullPath: '/locality-insights'
      preLoaderRoute: typeof LocalityInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-planner': {
      id: '/budget-planner'
      path: '/budget-planner'
      fullPath: '/budget-planner'
      preLoaderRoute: typeof BudgetPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  BudgetPlannerRoute: BudgetPlannerRoute,
  LocalityInsightsRoute: LocalityInsightsRoute,
  MarketAnalysisRoute: MarketAnalysisRoute,
  PredictorRoute: PredictorRoute,
  RecommendationsRoute: RecommendationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
